version: '3'

volumes:
  files:
    driver: local
  mysql:
    driver: local
  backup:
    driver: local
  files:
    driver: local
  redis:
    driver: local
  data-volume:
    driver: local
  irods-vault:
    driver: local
  irods-conf:
    driver: local

services:
  # ############################
  # iRODS
  # ############################
  postgres:
    image: eudat-docker-public.artie.ia.surfsara.nl/postgres:latest
    ports:
      - "5432"
    hostname: postgres.irods
    volumes:
      - data-volume:/var/lib/postgresql/10/main

  irods:
    image: eudat-docker-public.artie.ia.surfsara.nl/light_centos7_4_2_7:latest
    ports:
      - "127.0.0.1:1247:1247"
    depends_on:
      - postgres
    volumes:
      - irods-vault:/var/lib/irods
      - irods-conf:/etc/irods
    links:
      - postgres:postgres
    hostname: icat.irods
    command: /app/sleep.sh

  # ############################
  # owncloud
  # ############################
  owncloud:
    build:
      context: .
      dockerfile: owncloud/Dockerfile
    restart: always
    ports:
      - ${HTTP_PORT}:8080

    depends_on:
      - db
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
      - OWNCLOUD_LOGLEVEL=0
      - IRODS_OWNCLOUD_PASSWORD=${IRODS_OWNCLOUD_PASSWORD}
      - IRODS_ZONE=${IRODS_ZONE}
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - files:/mnt/data
    links:
      - irods:icat.irods
  db:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=owncloud
      - MARIADB_USERNAME=owncloud
      - MARIADB_PASSWORD=owncloud
      - MARIADB_DATABASE=owncloud
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
      - backup:/var/lib/backup

  redis:
    image: webhippie/redis:latest
    restart: always
    environment:
      - REDIS_DATABASES=1
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis:/var/lib/redis

